name: Z-Wave JS UI Garden Garage
version: "1.4.3"
slug: zwave_garden_garage
description: Z-Wave JS UI for Garden Garage controller
url: https://github.com/hassio-addons/addon-zwave-js-ui
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: ghcr.io/hassio-addons/zwave-js-ui/{arch}
